export const UPDATE_FETCHED_AFFIRMATIONS = 'UPDATE_FETCHED_AFFIRMATIONS';
export const FETCH_AFFIRMATIONS_FAILED = 'FETCH_AFFIRMATIONS_FAILED';
export const ADD_AFFIRMATION = 'ADD_AFFIRMATION';
export const DELETE_AFFIRMATION = 'DELETE_AFFIRMATION';
export const EDIT_AFFIRMATION = 'EDIT_AFFIRMATION';

export const UPDATE_FETCHED_VISION_BOARD = 'UPDATE_FETCHED_VISION_BOARD';
export const FETCH_VISION_BOARD_FAILED = 'FETCH_VISION_BOARD_FAILED';
export const ADD_VISION_BOARD = 'ADD_VISION_BOARD';
export const DELETE_VISION_BOARD = 'DELETE_VISION_BOARD';
export const EDIT_VISION_BOARD = 'EDIT_VISION_BOARD';

export const FETCH_DATA = 'FETCH_DATA';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';

export const ON_REGISTER = 'ON_REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
